export const ADD_ERROR = "ADD_ERROR";
export const REMOVE_ERROR = "REMOVE_ERROR";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const FETCH_USER = "FETCH_USER";
export const POST_CHECKOUT = "POST_CHECKOUT";
// DEPARTMENT TYPES
export const GET_DEPARTMENTS = "GET_DEPARTMENT";
export const POST_DEPARTMENT = "POST_DEPARTMENT";
export const DELETE_DEPARTMENT = "DELETE_DEPARTMENT";
export const UPDATE_DEPARTMENT = "UPDATE_DEPARTMENT";
// GENRE TYPES
export const GET_GENRES = "GET_GENRES";
export const UPDATE_GENRE = "UPDATE_GENRE";
export const DELETE_GENRE = "DELETE_GENRE";
export const POST_GENRE = "POST_GENRE";
// CATEGORY TYPES
export const GET_CATEGORIES = "LOAD_CATEGORIES";
export const POST_CATEGORY = "POST_CATEGORY";
export const DELETE_CATEGORY = "DELETE_CATEGORY";
export const UPDATE_CATEGORY = "UPDATE_CATEGORY";
// REVIEW TYPES
export const LOAD_REVIEWS = "LORD_REVIEWS";
export const REMOVE_REVIEW = "REMOVE_REVIEW";
export const POST_REVIEW = "POST_REVIEW ";
// PRODUCTS TYPES
export const VERIFY_PINCODE= "VERIFY_PINCODE";
export const GET_PRODUCT = "GET_PRODUCT";
export const LOAD_PRODUCTS = "LOaD_PRODUCTS";
export const REMOVE_PORDUCT = "REMOVE_PRODUCTS";
export const POST_PRODUCT = "POST_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
// CART TYPES
export const GET_CART = "GET_CART";
export const POST_CART = "POST_CART";
export const REDUCE_CART = "REMOVE_CART";
export const REMOVE_CART_ITEM = "REMOVE_CART_ITEM";
// ADDRESS TYPES
export const POST_ADDRESS = "POST_ADDRESS";
export const GET_ADDRESS = "GET_ADDRESS ";
export const REMOVE_ADDRESS = "REMOVE_ADDRESS";
// CHECKOUT TYPES
export const ADD_ADDRESS_TO_CHECKOUT_OBJECT = "ADD_ADDRESS_TO_CHECKOUT_OBJECT";
export const ADD_PAYMENT_MODE_TO_CHECKOUT_OBJECT =
  "ADD_PAYMENT_MODE_TO_CHECKOUT_OBJECT";
// ORDER TYPES
export const UPDATE_ORDER_STATUS ='UPDATE_ORDER_STATUS';
export const POST_ORDER = "POST_ORDER";
export const GET_ORDERS = "GET_ORDERS";
export const TRACK_ORDER = "TRACK_ORDER";
export const CANCEL_ORDER = "DELETE_ORDER"; 
// STAFFPICKS TYPES
export const GET_STAFFPICK = "GET_STAFFPICK";
export const UPDATE_STAFFPICK = "UPDATE_STAFFPICK";
export const POST_STAFFPICK = "POST_STAFFPICK";
export const DELETE_STAFFPICK = "DELETE_STAFFPICK";
